In [1]:
import pandas as pd
import sklearn

In [2]:
dados = pd.read_csv(r'C:\Users\User\Projetos an√°lise de dados\analise-dados\Projetos\Futebol\BRA.csv')

In [3]:
dados.head()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,1.75,3.86,5.25,1.76,3.87,5.31,1.69,3.50,4.90
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,2.83,3.39,2.68,2.83,3.42,2.70,2.59,3.23,2.58
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,1.60,4.04,6.72,1.67,4.05,7.22,1.59,3.67,5.64
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,2.49,3.35,3.15,2.49,3.39,3.15,2.35,3.26,2.84
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,1.96,3.53,4.41,1.96,3.53,4.41,1.89,3.33,3.89

In [12]:
dados.columns

Index(['Country', 'League', 'Season', 'Date', 'Time', 'Home', 'Away', 'HG',
       'AG', 'Res', 'PH', 'PD', 'PA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD',
       'AvgA', 'resultado'],
      dtype='object')

In [4]:

# agrupando as colunas em uma nova coluna
dados['resultado'] = dados.apply(lambda row: str(row['HG']) + " x " + str(row['AG']), axis=1)

In [5]:
dados.head()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,resultado
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,1.75,3.86,5.25,1.76,3.87,5.31,1.69,3.50,4.90,1.0 x 1.0
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,2.83,3.39,2.68,2.83,3.42,2.70,2.59,3.23,2.58,1.0 x 1.0
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,1.60,4.04,6.72,1.67,4.05,7.22,1.59,3.67,5.64,2.0 x 1.0
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,2.49,3.35,3.15,2.49,3.39,3.15,2.35,3.26,2.84,4.0 x 2.0
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,1.96,3.53,4.41,1.96,3.53,4.41,1.89,3.33,3.89,0.0 x 1.0

In [6]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4180 entries, 0 to 4179
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    4180 non-null   object
 1   League     4180 non-null   object
 2   Season     4180 non-null   int64
 3   Date       4180 non-null   object
 4   Time       4180 non-null   object
 5   Home       4180 non-null   object
 6   Away       4180 non-null   object
 7   HG         4179 non-null   float64
 8   AG         4179 non-null   float64
 9   Res        4179 non-null   object
 10  PH         4179 non-null   float64
 11  PD         4179 non-null   float64
 12  PA         4179 non-null   float64
 13  MaxH       4180 non-null   float64
 14  MaxD       4180 non-null   float64
 15  MaxA       4180 non-null   float64
 16  AvgH       4180 non-null   float64
 17  AvgD       4180 non-null   float64
 18  AvgA       4180 non-null   float64
 19  resultado  4180 non-null   object
dtypes: float64(11), int64(1), object(8)
memory usage: 653.2+ KB

In [7]:
# converter a coluna para int
dados['HG'] = dados['HG'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [10]:
# converter a coluna para int
dados['AG'] = dados['AG'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [14]:
dados['AG'] = dados['AG'].fillna(0).astype(int)

In [13]:
dados['HG'] = dados['HG'].fillna(0).astype(int)

In [15]:
dados.head()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,resultado
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1,1,D,1.75,3.86,5.25,1.76,3.87,5.31,1.69,3.50,4.90,1.0 x 1.0
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1,1,D,2.83,3.39,2.68,2.83,3.42,2.70,2.59,3.23,2.58,1.0 x 1.0
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2,1,H,1.60,4.04,6.72,1.67,4.05,7.22,1.59,3.67,5.64,2.0 x 1.0
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4,2,H,2.49,3.35,3.15,2.49,3.39,3.15,2.35,3.26,2.84,4.0 x 2.0
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0,1,A,1.96,3.53,4.41,1.96,3.53,4.41,1.89,3.33,3.89,0.0 x 1.0

In [16]:
dados['AG'] = dados['AG'].fillna(0).astype(int)

In [17]:
# converter a coluna para int
dados['AG'] = dados['AG'].astype(int)

In [18]:
# agrupando as colunas em uma nova coluna
dados['resultado'] = dados.apply(lambda row: str(row['HG']) + " x " + str(row['AG']), axis=1)

In [19]:
dados.head()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,resultado
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1,1,D,1.75,3.86,5.25,1.76,3.87,5.31,1.69,3.50,4.90,1 x 1
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1,1,D,2.83,3.39,2.68,2.83,3.42,2.70,2.59,3.23,2.58,1 x 1
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2,1,H,1.60,4.04,6.72,1.67,4.05,7.22,1.59,3.67,5.64,2 x 1
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4,2,H,2.49,3.35,3.15,2.49,3.39,3.15,2.35,3.26,2.84,4 x 2
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0,1,A,1.96,3.53,4.41,1.96,3.53,4.41,1.89,3.33,3.89,0 x 1

In [21]:
total_gols = dados.loc[dados['Home'] == 'Palmeiras', 'AG'].sum()
print(total_gols)

176

In [22]:
# agrupar os dados por time
gols_por_time = dados.groupby(['Home']).agg({'HG': 'sum', 'AG': 'sum'}).reset_index()

# somar os gols totais e adicionar a coluna correspondente
gols_por_time['Total'] = gols_por_time['HG'] + gols_por_time['AG']

# imprimir o resultado
print(gols_por_time)

              Home   HG   AG  Total
0       America MG   79   66    145
1     Athletico-PR  100   62    162
2      Atletico GO  102  111    213
3      Atletico-MG  380  191    571
4      Atletico-PR  193   91    284
5             Avai   75   96    171
6            Bahia  189  150    339
7      Botafogo RJ  221  177    398
8       Bragantino   91   62    153
9              CSA   17   24     41
10           Ceara  107   91    198
11  Chapecoense-SC  149  142    291
12     Corinthians  303  152    455
13        Coritiba  189  133    322
14        Criciuma   45   45     90
15        Cruzeiro  237  140    377
16          Cuiaba   35   35     70
17     Figueirense   86   82    168
18     Flamengo RJ  358  187    545
19      Fluminense  309  201    510
20       Fortaleza   96   64    160
21           Goias  149  120    269
22          Gremio  298  148    446
23   Internacional  307  161    468
24       Joinville   19   17     36
25       Juventude   37   42     79
26         Nautico   45   48     93
27       Palmeiras  333  176    509
28          Parana   13   23     36
29     Ponte Preta  122   94    216
30      Portuguesa   57   31     88
31      Santa Cruz   27   27     54
32          Santos  349  170    519
33       Sao Paulo  312  170    482
34    Sport Recife  189  146    335
35           Vasco  158  161    319
36         Vitoria  129  121    250

In [23]:
gols_por_time.to_csv('gols_por_time.csv', index=False)

In [25]:
gols_sofridos_por_time = dados.groupby(['Away']).agg({'HG': 'sum', 'AG': 'sum'}).reset_index()
gols_sofridos_por_time.columns = ['Time', 'Gols_sofridos_em_casa', 'Gols_sofridos_fora']
gols_sofridos_por_time['Gols_sofridos_total'] = gols_sofridos_por_time['Gols_sofridos_em_casa'] + gols_sofridos_por_time['Gols_sofridos_fora']
print(gols_sofridos_por_time)

              Time  Gols_sofridos_em_casa  Gols_sofridos_fora  \
0       America MG                    116                  55
1     Athletico-PR                     99                  78
2      Atletico GO                    150                  85
3      Atletico-MG                    276                 239
4      Atletico-PR                    160                  95
5             Avai                    134                  44
6            Bahia                    221                 139
7      Botafogo RJ                    239                 155
8       Bragantino                     83                  63
9              CSA                     34                   7
10           Ceara                    118                  88
11  Chapecoense-SC                    217                 112
12     Corinthians                    229                 198
13        Coritiba                    266                 132
14        Criciuma                     74                  32
15        Cruzeiro                    189                 154
16          Cuiaba                     44                  30
17     Figueirense                    137                  56
18     Flamengo RJ                    267                 258
19      Fluminense                    281                 217
20       Fortaleza                    113                  78
21           Goias                    193                 103
22          Gremio                    213                 193
23   Internacional                    227                 173
24       Joinville                     31                   7
25       Juventude                     71                  28
26         Nautico                     82                  21
27       Palmeiras                    230                 223
28          Parana                     34                   5
29     Ponte Preta                    149                  78
30      Portuguesa                     56                  32
31      Santa Cruz                     42                  18
32          Santos                    260                 191
33       Sao Paulo                    265                 220
34    Sport Recife                    251                 124
35           Vasco                    194                 122
36         Vitoria                    160                 104

    Gols_sofridos_total
0                   171
1                   177
2                   235
3                   515
4                   255
5                   178
6                   360
7                   394
8                   146
9                    41
10                  206
11                  329
12                  427
13                  398
14                  106
15                  343
16                   74
17                  193
18                  525
19                  498
20                  191
21                  296
22                  406
23                  400
24                   38
25                   99
26                  103
27                  453
28                   39
29                  227
30                   88
31                   60
32                  451
33                  485
34                  375
35                  316
36                  264

In [26]:
#gerando arquivo csv
gols_sofridos_por_time.to_csv('gols_sofridos_por_time.csv', index=False)

In [48]:
import pandas as pd

# carregar os dados do arquivo CSV
dados = pd.read_csv(r'C:\Users\User\Projetos an√°lise de dados\analise-dados\Projetos\Futebol\BRA.csv')

# criar fun√ß√£o para definir resultados de cada jogo
def definir_resultado(linha):
    if linha['Res'] == 'H':
        return 'Vitoria'
    elif linha['Res'] == 'A':
        return 'Derrota'
    else:
        return 'Empate'
# criar fun√ß√£o para calcular a pontua√ß√£o
def calcular_pontos(linha):
    return linha['Vitoria'] * 3 + linha['Empate']



# agrupar os dados por time e resultado e calcular as contagens
resultados_por_time = dados.groupby(['Home', 'Resultado']).size().reset_index(name='Contagem')

# pivotar a tabela para ter uma coluna para cada tipo de resultado
resultados_por_time = resultados_por_time.pivot(index='Home', columns='Resultado', values='Contagem')

# preencher valores NaN com zero
resultados_por_time = resultados_por_time.fillna(0)

# calcular o n√∫mero total de jogos de cada time
resultados_por_time['Total'] = resultados_por_time['Vitoria'] + resultados_por_time['Derrota'] + resultados_por_time['Empate']
# aplicar fun√ß√£o para criar coluna "Pontos"
resultados_por_time['Pontos'] = resultados_por_time.apply(calcular_pontos, axis=1)


# salvar o resultado em um arquivo CSV
resultados_por_time.to_csv('resultados_por_time.csv')

KeyError: 'Resultado'

In [ ]:
como criar um arquivo de banco de dados reunindo informa√ßoes de gols feitos em casa, fora, total de gols, gols sofridos em casa, fora, total e numero de vitorias, empates e vitorias

In [35]:
# Calculando a pontua√ß√£o de cada time
resultados_por_time['Pontos'] = resultados_por_time['Vitoria']*3 + resultados_por_time['Empate']

# Ordenando o DataFrame pela pontua√ß√£o de forma decrescente
resultados_por_time = resultados_por_time.sort_values(by='Pontos', ascending=False)

# Salvando o resultado em um arquivo CSV
resultados_por_time.to_csv('pontuacao.csv', index=False)

In [40]:
# Agrupando por time e contabilizando vit√≥rias, derrotas e empates
resultados_por_time = dados.groupby(['Home']).agg({'Res': lambda x: x.map({'H': 1, 'D': 0, 'A': -1}).sum(),
                                                   'Away': 'count'}).reset_index()

# Renomeando as colunas
resultados_por_time = resultados_por_time.rename(columns={'Res': 'Vitoria', 'Away': 'Jogos'})

# Adicionando colunas de derrotas e empates
resultados_por_time['Derrota'] = resultados_por_time['Jogos'] - resultados_por_time['Vitoria']
resultados_por_time['Empate'] = resultados_por_time['Jogos'] - resultados_por_time['Vitoria'] - resultados_por_time['Derrota']

# Adicionando coluna de pontos
resultados_por_time['Pontos'] = resultados_por_time['Vitoria']*3 + resultados_por_time['Empate']

# Ordenando o DataFrame pela pontua√ß√£o de forma decrescente
resultados_por_time = resultados_por_time.sort_values(by='Pontos', ascending=False)

# Exibindo os nomes dos times e salvando o resultado em um arquivo CSV
resultados_por_time[['Home', 'Vitoria','Empate','Derrota','Pontos']].to_csv('pontuacao.csv', index=False)

In [52]:
import pandas as pd

#carregar os dados do arquivo CSV
dados = pd.read_csv(r'C:\Users\User\Projetos an√°lise de dados\analise-dados\Projetos\Futebol\BRA.csv')

#criar fun√ß√£o para definir resultados de cada jogo
def definir_resultado(linha):
    if linha['Res'] == 'H':
        return 'Vitoria'
    elif linha['Res'] == 'A':
        return 'Derrota'
    else:
        return 'Empate'

#aplicar fun√ß√£o para criar coluna "Resultado"
dados['Resultado'] = dados.apply(definir_resultado, axis=1)

#agrupar os dados por time e resultado e calcular as contagens
resultados_por_time = dados.groupby(['Home', 'Resultado']).size().reset_index(name='Contagem')

#pivotar a tabela para ter uma coluna para cada tipo de resultado
resultados_por_time = resultados_por_time.pivot(index='Home', columns='Resultado', values='Contagem')

#preencher valores NaN com zero
resultados_por_time = resultados_por_time.fillna(0)

#calcular o n√∫mero total de jogos de cada time
resultados_por_time['Total'] = resultados_por_time['Vitoria'] + resultados_por_time['Derrota'] + resultados_por_time['Empate']

#calcular a pontua√ß√£o de cada time
resultados_por_time['Pontos'] = resultados_por_time['Vitoria'] * 3 + resultados_por_time['Empate']

#ordenar o DataFrame pela pontua√ß√£o de forma decrescente
resultados_por_time = resultados_por_time.sort_values(by='Pontos', ascending=False)

#salvar o resultado em um arquivo CSV
resultados_por_time.to_csv('resultados_por_time.csv')

In [54]:
import pandas as pd
import sqlite3

# carregar os dados do arquivo CSV
dados = pd.read_csv(r'C:\Users\User\Projetos an√°lise de dados\analise-dados\Projetos\Futebol\BRA.csv')

# criar fun√ß√£o para definir resultados de cada jogo
def definir_resultado(linha):
    if linha['Res'] == 'H':
        return 'Vitoria'
    elif linha['Res'] == 'A':
        return 'Derrota'
    else:
        return 'Empate'

# aplicar fun√ß√£o para criar coluna "Resultado"
dados['Resultado'] = dados.apply(definir_resultado, axis=1)

# agrupar os dados por time e calcular as estat√≠sticas
gols_por_time = dados.groupby(['Home']).agg({'HG': 'sum', 'AG': 'sum'}).reset_index()
gols_sofridos_por_time = dados.groupby(['Home']).agg({'AG': 'sum', 'HG': 'sum'}).reset_index()
resultados_por_time = dados.groupby(['Home', 'Resultado']).size().reset_index(name='Contagem')
resultados_por_time = resultados_por_time.pivot(index='Home', columns='Resultado', values='Contagem').fillna(0)
resultados_por_time['Total'] = resultados_por_time['Vitoria'] + resultados_por_time['Derrota'] + resultados_por_time['Empate']
resultados_por_time['Pontos'] = resultados_por_time['Vitoria']*3 + resultados_por_time['Empate']

# juntar as informa√ß√µes em um √∫nico dataframe
dados_agrupados = gols_por_time.merge(gols_sofridos_por_time, on='Home', suffixes=['_feitos', '_sofridos'])
dados_agrupados = dados_agrupados.merge(resultados_por_time, on='Home')

# criar conex√£o com o banco de dados
conn = sqlite3.connect('dados_futebol.db')

# criar tabela para armazenar os dados
conn.execute('''CREATE TABLE IF NOT EXISTS dados_futebol
                (time TEXT, gols_casa INTEGER, gols_fora INTEGER, total_gols INTEGER, 
                 gols_sofridos_casa INTEGER, gols_sofridos_fora INTEGER, total_gols_sofridos INTEGER, 
                 vitorias INTEGER, empates INTEGER, derrotas INTEGER, total_jogos INTEGER, pontos INTEGER)''')

# inserir os dados na tabela
for row in dados_agrupados.itertuples(index=False):
    conn.execute(f"INSERT INTO dados_futebol VALUES ('{row.Home}', {row.HG_feitos}, {row.AG_feitos}, {row.HG_feitos + row.AG_feitos}, {row.HG_sofridos}, {row.AG_sofridos}, {row.HG_sofridos + row.AG_sofridos}, {row.Vitoria}, {row.Empate}, {row.Derrota}, {row.Total}, {row.Pontos})")

# commitar as mudan√ßas e fechar a conex√£o
conn.commit()
conn.close()

In [55]:
import pandas as pd
import sqlite3

# conectar com o banco de dados
conn = sqlite3.connect('dados_futebol.db')

# executar consulta SQL para obter os dados
dados = pd.read_sql_query("SELECT * FROM dados_futebol", conn)

# salvar os dados em um arquivo CSV
dados.to_csv('dados_futebol.csv', index=False)

# fechar a conex√£o com o banco de dados
conn.close()